### ISSUE TITLE
Fix Extension Initiation Issue

### ISSUE THREAD

**Issue by sil6s** [sil6s/ExtensionTest#17]
Extension launch is only initiated when browser refresh button is clicked. 
Check API contained in service_worker.js file.

**Comment by sil6s** [comment]
ITSC Project Management: sil6s started this project at 9:13am (EST).

**Comment by sil6s** [comment]
Your comment hgfghf here

**Comment by sil6s** [comment]
Your comment goes here

**Comment by sil6s** [comment]
Your comment goes here

**Comment by sil6s** [comment]
Your comment goes here

**Comment by sil6s** [comment]
Your comment goes here

**Comment by sil6s** [comment]
Your comment goes heress

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS:

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 1:51:44 PM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 1:55:44 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 1:57:05 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 2:06:17 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 2:17:42 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 2:19:24 PM

**Comment by sil6s** [comment]
ITSC PMS: User resumed issue

**Comment by sil6s** [comment]
ITSC PMS: Started issue at ${currentTime}`

**Comment by HanksJ06** [comment]
ITSC PMS: User stopped issue at 2:32:14 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User stopped issue at 2:33:37 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User stopped issue at 2:36:25 PM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 10:20:50 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 10:21:59 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 10:22:38 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 10:23:50 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 10:23:50 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 10:24:02 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 10:26:16 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 10:26:25 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 10:26:55 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 10:27:06 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 10:27:52 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 10:36:14 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 10:36:18 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 10:36:23 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 10:37:35 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 10:37:40 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 10:41:50 AM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 11:02:59 AM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 11:04:31 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 11:12:12 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 11:24:39 AM

**Comment by sil6s** [comment]
ITSC PMS: User started issue at 11:26:49 AM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 11:29:56 AM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 11:30:33 AM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 12:48:09 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 12:48:39 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 1:07:50 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 1:08:41 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 1:12:18 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 1:12:31 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 1:15:43 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 1:16:23 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 1:16:43 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 1:25:49 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 1:28:27 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 1:29:13 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 1:39:21 PM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 2:07:05 PM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:08:15 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:08:18 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:08:21 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:08:24 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:08:27 AM

**Comment by sil6s** [comment]
ITSC PMS: Timer state unknown at 9:08:30 AM

**Comment by sil6s** [comment]
ITSC PMS: Timer state unknown at 9:09:53 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:11:35 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:11:41 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:11:44 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work timer on issue at 9:11:45 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:11:50 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:13:12 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:13:15 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:13:18 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:13:21 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:13:24 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:15:51 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:15:54 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:15:57 AM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 9:17:04 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:17:43 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:17:46 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:20:03 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:20:07 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:20:10 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:22:45 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:22:48 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:22:51 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:23:16 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work timer on issue at 9:26:51 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:27:35 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work on issue at 9:27:36 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:27:41 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:27:57 AM

**Comment by sil6s** [comment]
ITSC PMS: User stopped work on issue at 9:28:04 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:28:12 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work on issue at 9:28:16 AM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 9:28:36 AM

**Comment by HanksJ06** [comment]
ITSC PMS: User started issue at 9:28:56 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:31:48 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:31:53 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work on issue at 9:31:57 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:32:45 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:32:50 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work on issue at 9:32:54 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:34:42 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:35:12 AM

**Comment by sil6s** [comment]
ITSC PMS: User stopped work on issue at 9:35:16 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:35:24 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work on issue at 9:35:28 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:43:37 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work on issue at 9:43:42 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:43:46 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:45:05 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:45:33 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:47:51 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:47:55 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work on issue at 9:47:59 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:49:01 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:51:32 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:53:13 AM

**Comment by HanksJ06** [comment]
ITSC PMS: User started work on issue at 9:53:40 AM

**Comment by HanksJ06** [comment]
ITSC PMS: User started work on issue at 9:53:50 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:54:06 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:54:11 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:54:51 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work on issue at 9:54:58 AM

**Comment by HanksJ06** [comment]
ITSC PMS: User started work on issue at 9:55:23 AM

**Comment by HanksJ06** [comment]
ITSC PMS: User started work on issue at 9:55:51 AM

**Comment by HanksJ06** [comment]
ITSC PMS: User started work on issue at 9:56:00 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 9:59:36 AM

**Comment by sil6s** [comment]
ITSC PMS: User stopped work on issue at 9:59:42 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:01:49 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work on issue at 10:01:53 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:03:01 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:07:56 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:08:02 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:08:08 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:08:12 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:08:22 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work on issue at 10:09:46 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:09:47 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work on issue at 10:12:13 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:12:17 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work on issue at 10:12:29 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:13:40 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:14:30 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work on issue at 10:14:35 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:14:36 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work on issue at 10:15:52 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:15:56 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work on issue at 10:17:20 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:17:23 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:19:19 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work on issue at 10:19:25 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:19:30 AM

**Comment by sil6s** [comment]
ITSC PMS: User paused work on issue at 10:19:37 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:19:40 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 10:24:11 AM

**Comment by HanksJ06** [comment]
ITSC PMS: User started work on issue at 10:45:55 AM

**Comment by HanksJ06** [comment]
ITSC PMS: User paused work on issue at 10:46:02 AM

**Comment by sil6s** [comment]
ITSC PMS: User started work on issue at 11:22:09 AM

**Comment by HanksJ06** [comment]
ITSC PMS: User started work on issue at 1:41:45 PM

**Comment by HanksJ06** [comment]
## ITSC Project Management System:

### User started work on issue at 1:41:58 PM on ( date here)

**Comment by HanksJ06** [comment]
## ITSC Project Management System:

### User started work on issue at 1:45:31 PM on Fri Jun 07 2024

**Comment by HanksJ06** [comment]
## ITSC Project Management System:

### User started work on issue at 1:54:18 PM on Fri Jun 07 2024

**Comment by HanksJ06** [comment]
## ITSC Project Management System:

### User started work on issue at 1:58:40 PM on Fri Jun 07 2024

**Comment by HanksJ06** [comment]
## ITSC Project Management System:

### User started work on issue at 2:03:03 PM on 6/7/2024

**Comment by HanksJ06** [comment]
## ITSC Project Management System:

### User started work on issue at 2:03:27 PM on 6/7/2024

**Comment by HanksJ06** [comment]
## ITSC Project Management System:

### User started work on issue at 2:04:05 PM on 6/7/2024

**Comment by HanksJ06** [comment]
## ITSC Project Management System:

### User started work on issue at 2:04:36 PM on 6/7/2024

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###
